### ISSUE TITLE
asyndeton

### ISSUE THREAD

**Issue by jonathanrobie** [biblicalhumanities/treedown#24]
We need a good way to represent asyndeton.  Perhaps `:`?

```
        s πᾶσα σὰρξ 
        pc ὡς χόρτος,
    καὶ 
        s πᾶσα δόξα αὐτῆς 
        pc ὡς ἄνθος χόρτου·
   :
        v ἐξηράνθη 
        s ὁ χόρτος,
    καὶ 
        s τὸ ἄνθος 
        v ἐξέπεσεν·
```

**Comment by jtauber** [comment]
works for me

**Comment by jtauber** [comment]
Not only do I continue to like this, I actually think it's useful to use for the first clause.

In your example above, it's a little weird that there's an initial indentation but this can be solved by just saying:

```
    :
        s πᾶσα σὰρξ 
        pc ὡς χόρτος,
    καὶ 
        s πᾶσα δόξα αὐτῆς 
        pc ὡς ἄνθος χόρτου·
    :
        v ἐξηράνθη 
        s ὁ χόρτος,
    καὶ 
        s τὸ ἄνθος 
        v ἐξέπεσεν·
```

**Comment by jtauber** [comment]
Similarly with John 1.1, you could start with a `:` at the same level as the `καὶ`

**Comment by jtauber** [comment]
Another example is:

```
:
  o ταύτην
  v ἐποίησεν
  o ἀρχὴν τῶν σημείων
  s ὁ Ἰησοῦς
  + ἐν Κανὰ τῆς Γαλιλαίας
καὶ
  v ἐφανέρωσεν
  o τὴν δόξαν αὐτοῦ
καὶ
  v ἐπίστευσαν
  o εἰς αὐτὸν
  s οἱ μαθηταὶ αὐτοῦ.
```

**Comment by jtauber** [comment]
Another example also from John 2 (punting on how to do direct speech as I'm not sure what we've decided for that):

```
καὶ
  v λέγει
  o.i αὐτοῖς·
  ??
    :
      v Ἀντλήσατε
      + νῦν
    καὶ
      v φέρετε
      o.i τῷ ἀρχιτρικλίνῳ·
```

If I don't use `:` above I think it leads to weird indentation.

**Comment by jonathanrobie** [comment]
> Not only do I continue to like this, I actually think it's useful to use for the first clause.
>
> In your example above, it's a little weird that there's an initial indentation but this can be solved by just saying:

Can you convince me?  Here's my starting point:  I think the indentation for the first clause has a clear meaning that needs to be learned, and I don't know what an initial colon is supposed to mean.  Remember that the formal definition of Treedown is in terms of bracket notation - for asyndeton, the colon tells me to handle brackets differently, for the initial colon, I don't think it does.

**Comment by jtauber** [comment]
Maybe it's just I'm so used to Python, but I find the multiple indentation weird looking (or an analysis that starts with an indentation). I can see why it's probably different from `:` used for indentation but I'm trying to avoid a completely blank label for a constituent.

Although my motivation was purely plain text expanded treedown, it does also occur to me that multiple indentation without some sort of non-blank label also makes it impossible to implement my collapsible UI for treedown as there's no handle to toggle.

**Comment by jonathanrobie** [comment]
I think you are asking indentation to do what brackets do.  Why not use the bracketed form or the XML form in Python?

**Comment by jtauber** [comment]
I thought indentation was _supposed_ to do what brackets do. To quote your blog post:

> In Treedown, an indentation level is equivalent to a bracket

I'm just saying I aesthetically find multiple indentations at once (or an initial indentation) odd looking. Or put another way: I'm proposing no blank nodes in the tree. This has the added benefit that every node has a "handle" for collapsing.

Originally I was proposing`:` but I'm fine keeping that for asyndeton. In my latest treedowning, I've tentatively been using `.`

**Comment by jonathanrobie** [comment]
This issue was about asyndeton - shall we close it?  I opened issue #32 for the other issue you raised.

**Comment by jtauber** [comment]
Are we all good with `:` for asyndeton? I guess it's been a month for anyone else to chime in, and there's been no objections (and a +1 from me).

Where are these decisions being documented for reference?

**Comment by jonathanrobie** [comment]
Closed, adopting `:`.

See https://github.com/biblicalhumanities/treedown/blob/master/decisions.md
