### ISSUE TITLE
John 2.14

### ISSUE THREAD

**Issue by jtauber** [biblicalhumanities/treedown#29]
> εὗρεν ἐν τῷ ἱερῷ τοὺς πωλοῦντας βόας καὶ πρόβατα καὶ περιστερὰς καὶ τοὺς κερματιστὰς καθημένους

Not 100% sure how best to treedown this.

We have a noun phrase:

```
    τοὺς
        v.part πωλοῦντας
        o βόας καὶ πρόβατα καὶ περιστερὰς
```

conjoined with another noun phrase:

```
    τοὺς κερματιστὰς
```

This conjoined phrase is both the object of εὗρεν and the subject of καθημένους.

Furthermore, I think ἐν τῷ ἱερῷ is really modifying καθημένους

Not sure how best to convey that analysis.

**Comment by jonathanrobie** [comment]
At a coarser granularity, I understand this as follows:

```
v εὗρεν 
+ ἐν τῷ ἱερῷ 
o 
        τοὺς πωλοῦντας βόας καὶ πρόβατα καὶ περιστερὰς 
    καὶ 
        τοὺς κερματιστὰς καθημένους
```

At a finer granularity:

```
v εὗρεν 
+ ἐν τῷ ἱερῷ 
o 
        s τοὺς 
        v.part πωλοῦντας 
        o βόας καὶ πρόβατα καὶ περιστερὰς 
    καὶ 
        s τοὺς κερματιστὰς 
        v.part καθημένους
```

> Furthermore, I think ἐν τῷ ἱερῷ is really modifying καθημένους. Not sure how best to convey that analysis.

The closest I know is to relate it to the verb εὗρεν like this:

```
v εὗρεν 
+ ἐν τῷ ἱερῷ 
o 
        s τοὺς 
        v.part πωλοῦντας 
        o βόας καὶ πρόβατα καὶ περιστερὰς 
    καὶ 
        s τοὺς κερματιστὰς 
v.part καθημένους
```

**Comment by jtauber** [comment]
I'm actually now leaning towards treating ἐν τῷ ἱερῷ as an adjunct to εὗρεν

It _feels_ like it must (also?) modify the καθημένους but that might just be my English intuitions getting in the way. (In English, I couldn't say "*I found him sitting" without a locative)

**Comment by jtauber** [comment]
In light of that comment, I think the "coarser granularity" analysis is fine. I need to think more about your handling of  τοὺς πωλοῦντας βόας καὶ πρόβατα καὶ περιστερὰς  and τοὺς κερματιστὰς καθημένους, though

**Comment by jonathanrobie** [comment]
One change I would make is to pull the participle into the subject.  If only the κερματιστὰς were sitting, then:

```
v εὗρεν 
+ ἐν τῷ ἱερῷ 
o 
        s τοὺς πωλοῦντας 
        o βόας καὶ πρόβατα καὶ περιστερὰς 
    καὶ 
        s τοὺς κερματιστὰς 
        v.part καθημένους
```

If τοὺς πωλοῦντας were also sitting, then:

```
v εὗρεν 
+ ἐν τῷ ἱερῷ 
o 
        s τοὺς πωλοῦντας 
        o βόας καὶ πρόβατα καὶ περιστερὰς 
    καὶ 
        s τοὺς κερματιστὰς 
v.part καθημένους
```

One test I use:  what happens to the rest of the sentence if I leave these constituents out:

```
v εὗρεν 
o 
        s τοὺς πωλοῦντας 
        o βόας καὶ πρόβατα καὶ περιστερὰς 
    καὶ 
        s τοὺς κερματιστὰς 
```

To me, this still makes sense, and the relationships are unchanged among the constituents that remain.  So what happens if we combine them into one adjunct?

```
v εὗρεν 
+ ἐν τῷ ἱερῷ καθημένους
o 
        s τοὺς πωλοῦντας 
        o βόας καὶ πρόβατα καὶ περιστερὰς 
    καὶ 
        s τοὺς κερματιστὰς 
```

To me, this has the same basic meaning as the second analysis in this post.

**Comment by jonathanrobie** [comment]
@jtauber Can I close this issue?  Have we accounted for the passage?

**Comment by jtauber** [comment]
Yes, I think that last analysis suffices.
