### ISSUE TITLE
discontinuous noun phrase in John 2.15b

### ISSUE THREAD

**Issue by jtauber** [biblicalhumanities/treedown#30]
Not sure how best to represent the τῶν κολλυβιστῶν in the second part of John 2.15 as modifying the τὰ κέρματα

```
καὶ
    ?? τῶν κολλυβιστῶν
    v ἐξέχεεν
    o τὰ κέρματα
καὶ
    o τὰς τραπέζας
    v ἀνέστρεψεν,
```

**Comment by jonathanrobie** [comment]
Isn't that just one object that is split by the verb?  I'd handle it like other split constituents:

```
o τῶν κολλυβιστῶν
v ἐξέχεεν
o τὰ κέρματα
```

**Comment by jtauber** [comment]
Yeah, I guess that's consistent with not analysing the structure within the noun phrase
