### ISSUE TITLE
δύναται + inf

### ISSUE THREAD

**Issue by jtauber** [biblicalhumanities/treedown#31]
John 3.1–15 has lots of δύναται + inf constructions but I'm not 100% sure how to treedown them when the infinitive has objects of its own.

In these constructions, the infinitive is a complement of the main verb so could be put at the same level (like other complements like and `o`):

```
v δύναται
v.inf ἰδεῖν
```

But this raises the question of what level objects of the infinitive go. For example

```
v οὐ δύναται
v.inf ἰδεῖν
o τὴν βασιλείαν τοῦ θεοῦ.
```

just seems wrong. We COULD indent the infinitive and its complements:

```
v οὐ δύναται
    v.inf ἰδεῖν
    o τὴν βασιλείαν τοῦ θεοῦ.
```

but that seems inconsistent given other complements are not so indented. I could potentially live with it, though, especially as it supports the cases when the object of the infinitive is before the infinitive:

```
v δύναται
    o ταῦτα τὰ σημεῖα
    v.inf ποιεῖν
```

I still question how to do μὴ δύναται εἰς τὴν κοιλίαν τῆς μητρὸς αὐτοῦ δεύτερον εἰσελθεῖν καὶ γεννηθῆναι;

I guess one possibility is:

```
v μὴ δύναται
    + εἰς τὴν κοιλίαν τῆς μητρὸς αὐτοῦ
    + δεύτερον
        v.inf εἰσελθεῖν
    καὶ
        v.inf γεννηθῆναι;
```

although as I've commented on #24, I really don't like that handling of indentation for coordination, in this case in particular, because it makes it look like εἰσελθεῖν is governed by δεύτερον which is the exact opposite of what it should be.

**Comment by jonathanrobie** [comment]
I don't use v.inf when it is the object of another verb.  I would do this:

```
v οὐ δύναται
o
    v.inf ἰδεῖν
    o τὴν βασιλείαν τοῦ θεοῦ.
```

**Comment by jtauber** [comment]
Ah yes, I like this. Collapses nicely too.

**Comment by jtauber** [comment]
One thing that's missing here (which I also raised in the context of other clausal complements) is δύναμαι only takes clausal complements, not phrasal complement and just using `o` glosses over this.

That might not be a showstopper, though. I could scan the children of `o` to see if they included a `v.inf` and that would tell me the type of `o` it was.

**Comment by jonathanrobie** [comment]
Our job here is to describe the instance, and if the object is a clause in every instance, we have done our job.

But there's a guidelines issue:  We are currently using `v.inf` and `v.part` as a shortcut, the relevant verb generally functions as an adjunct, an object, etc.  The shortcut is convenient but a little sloppy. If we didn't allow it, markdown would be harder but more precise.

**Comment by jtauber** [comment]
> Our job here is to describe the instance, and if the object is a clause in every instance, we have done our job.

That's why I don't think it's a showstopper.

I still keep coming back, though, to the question: if we use `o` for pretty much all non-subject complements and we bother to distinguish direct, indirect, and second objects with their own labels, why not this type of "object"?

I think the `.inf` and `.part` are vital to a clear annotation. Not sure what's sloppy about them. Within their clause, they are `v` but the fact they use `.inf` or`.part` massively alters their role in the higher clause and so not including the `.inf` or `.part` would obscure that.

**Comment by jonathanrobie** [comment]
@jtauber I think we have an answer to the δύναται + inf issue, but you raise another about complements.

Can I close this and discuss complements in a separate issue?

**Comment by jtauber** [comment]
Yeah, we can have another issue for that.
